Add site heatmap plots to msps_dimorphism workflow

diff --git a/analysis/workflows/msps_dimorphism/Snakefile b/analysis/workflows/msps_dimorphism/Snakefile
--- a/analysis/workflows/msps_dimorphism/Snakefile
+++ b/analysis/workflows/msps_dimorphism/Snakefile
@@ -17,10 +17,11 @@ output_gram_build = Path(f'{config["gram_builds_dir"]}/{config["gene_list_name"]
 output_gtyping = output_base / "gtyping"
 output_msas = output_base / "msas"
 output_sequences = output_msas / "sequences"
-output_trees = output_base / "trees"
-output_drawn_trees = output_trees / "plots"
-output_tree_splits = output_trees / "splits"
+output_trees = output_base / "phylo_trees"
+#output_drawn_trees = output_trees / "plots"
+output_tree_splits = output_trees / "tree_splits"
 output_graphs = output_base / "graphs"
+output_heatmaps = output_base / "heatmaps"
 
 mk_output_dirs(dir())
 
@@ -36,8 +37,8 @@ samples = get_bams(config["pf3k"]["bams_filelist"]) # in utils.py
 
 rule all:
 	input:
-		graphs=expand(f"{output_graphs}/{{gene}}/{{filename}}.gml", gene = genes, filename = ["all_samples", "partition_1", "partition_2"]),
-		res_tree_plots=expand(f"{output_drawn_trees}/{{gene}}.pdf", gene = genes),
+		graphs=expand(f"{output_graphs}/{{gene}}_{{filename}}.gml", gene = genes, filename = ["all_samples", "partition_1", "partition_2"]),
+		heatmaps=expand(f"{output_heatmaps}/{{gene}}_hmap.pdf", gene = genes)
 
 rule build:
 	input:
@@ -151,30 +152,17 @@ rule phylo_trees:
 		fi
 		"""
 	
-rule draw_trees:
-	input:
-		f"{output_trees}/{{gene}}/RAxML_bestTree.{{gene}}"
-	output:
-		f"{output_drawn_trees}/{{gene}}.pdf"
-	params:
-		script=f'{config["scripts"]}/{WORKFLOW}/plot_tree.R',
-		gmtools_commit=GMTOOLS_COMMIT
-	shell:
-		"""
-		output_prefix={output}
-		output_prefix=${{output_prefix%.pdf}}
-		Rscript {params.script} {input} ${{output_prefix}} 'gmtools_commit:{params.gmtools_commit}'
-		"""
-
 rule tree_basal_split:
 	input:
 		f"{output_trees}/{{gene}}/RAxML_bestTree.{{gene}}"
 	output:
-		f"{output_tree_splits}/{{gene}}.basal_split"
+		split=f"{output_tree_splits}/{{gene}}.basal_split",
+		plot=f"{output_tree_splits}/{{gene}}.pdf",
 	params:
-		script=f'{config["scripts"]}/{WORKFLOW}/tree_partition.py'
+		script=f'{config["scripts"]}/{WORKFLOW}/tree_partition.py',
+		output_prefix=f"{output_tree_splits}/{{gene}}"
 	shell:
-		"python3 {params.script} {input} {output}"
+		"python3 {params.script} {input} {params.output_prefix}"
 
 rule build_graphs:
 	input:
@@ -182,11 +170,11 @@ rule build_graphs:
 		genes_bed=config["genes_bed"],
 		tree_split=f"{output_tree_splits}/{{gene}}.basal_split",
 	output:
-		all_samples=f"{output_graphs}/{{gene}}/all_samples.gml",
-		partition1=f"{output_graphs}/{{gene}}/partition_1.gml",
-		partition2=f"{output_graphs}/{{gene}}/partition_2.gml",
+		all_samples=f"{output_graphs}/{{gene}}_all_samples.gml",
+		partition1=f"{output_graphs}/{{gene}}_partition_1.gml",
+		partition2=f"{output_graphs}/{{gene}}_partition_2.gml",
 	params:
-		output_dir=f"{output_graphs}/{{gene}}",
+		output_prefix=f"{output_graphs}/{{gene}}",
 		script=f'{config["scripts"]}/{WORKFLOW}/get_site_diversity_graphs.py'
 	shell:
 		"""
@@ -197,7 +185,28 @@ rule build_graphs:
 		adj_start=$((${{elems[1]}} + 1))
 		reg="${{elems[0]}}:${{adj_start}}-${{elems[2]}}"
 
-		python3 {params.script} {input.res_json} {params.output_dir} --region $reg # for all_samples
-		python3 {params.script} {input.res_json} {params.output_dir} --region $reg -p {input.tree_split} # for partitions
+		python3 {params.script} {input.res_json} {params.output_prefix} --region $reg # for all_samples
+		python3 {params.script} {input.res_json} {params.output_prefix} --region $reg -p {input.tree_split} # for partitions
 		"""
 	
+rule build_heatmaps:
+	input:
+		res_json=f"{output_gtyping}/combined.json",
+		genes_bed=config["genes_bed"],
+	output:
+		hapg_data=f"{output_heatmaps}/{{gene}}_hapgs.tsv",
+		plot=f"{output_heatmaps}/{{gene}}_hmap.pdf",
+	params:
+		output_prefix=f"{output_heatmaps}/{{gene}}",
+		script=f'{config["scripts"]}/{WORKFLOW}/hapg_heatmap.py'
+	shell:
+		"""
+		# Produce region
+		match=$(grep -w {wildcards.gene} {input.genes_bed})
+		if [[ -z ${{match}} ]]; then echo "ERROR: No match of gene name in bed file"; exit 1; fi
+		IFS="\t"; elems=($match)	
+		adj_start=$((${{elems[1]}} + 1))
+		reg="${{elems[0]}}:${{adj_start}}-${{elems[2]}}"
+
+		python3 {params.script} {input.res_json} {params.output_prefix} --region $reg
+		"""
